src/Entity/ClothingPiece.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Normalizer\DataUriNormalizer;
use Symfony\Component\Serializer\Serializer;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClothingPieceRepository")
 */
class ClothingPiece
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Size;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Color;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Style;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="clothingPieces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    private $normalizer;

    /**
     * @ORM\Column(type="string", length=100000000)
     */
    private $Uri;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Type;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $selected;

    public function __construct()
    {
        $this->userClothingPieces = new ArrayCollection();
        $this->serializer = new Serializer();
        $this->normalizer = new DataUriNormalizer();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSize(): ?string
    {
        return $this->Size;
    }

    public function setSize(string $Size): self
    {
        $this->Size = $Size;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->Color;
    }

    public function setColor(string $Color): self
    {
        $this->Color = $Color;

        return $this;
    }

    public function getStyle(): ?string
    {
        return $this->Style;
    }

    public function setStyle(string $Style): self
    {
        $this->Style = $Style;

        return $this;
    }

    /**
     * @return Collection|UserClothingPiece[]
     */
    public function getUserClothingPieces(): Collection
    {
        return $this->userClothingPieces;
    }

    public function addUserClothingPiece(UserClothingPiece $userClothingPiece): self
    {
        if (!$this->userClothingPieces->contains($userClothingPiece)) {
            $this->userClothingPieces[] = $userClothingPiece;
            $userClothingPiece->setClothingPiece($this);
        }

        return $this;
    }

    public function removeUserClothingPiece(UserClothingPiece $userClothingPiece): self
    {
        if ($this->userClothingPieces->contains($userClothingPiece)) {
            $this->userClothingPieces->removeElement($userClothingPiece);
            // set the owning side to null (unless already changed)
            if ($userClothingPiece->getClothingPiece() === $this) {
                $userClothingPiece->setClothingPiece(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getUri()
    {
        return $this->Uri;
    }

    /**
     * @param mixed $Uri
     */

    public function setUri($Uri)
    {
        $normalizer = new DataUriNormalizer();
        $Uri = $normalizer->normalize($Uri);
        $this->Uri = $Uri;
        return $this;
    }


    public function uti() {

    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getSelected(): ?bool
    {
        return $this->selected;
    }

    public function setSelected(?bool $selected): self
    {
        $this->selected = $selected;

        return $this;
    }
}

src/Controller/MemberController.php
<?php

namespace App\Controller;

use App\Entity\ClothingPiece;
use App\Entity\User;
use App\Form\Type\ClothingPieceType;
use App\Form\Type\FaceImageType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MemberController extends AbstractController
    /**
     * @Route("/member")
     */
{
    /**
     * @Route("/home", name="member_home")
     */
    public function homepage() {
        return $this->render('member/homepage.html.twig');
    }

    /**
     * @Route("/clothes_add", name="clothes_add")
     */
    public function formtest(Request $request)
    {
        $clothing = new ClothingPiece();

        $form = $this->createForm(ClothingPieceType::class, $clothing);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            /**$var UploadedFile $imageFile*/
            $imageFile = $form->get('image_file_name')->getData();
            if($imageFile) {
                $uri = $clothing->setUri($imageFile);
                //Move the file to the directory where images are stored
            }
            $clothing = $form->getData();
            $user = $this->getUser();
            $clothing->setUser($user);
            $em = $this->getDoctrine()->getManager();
            $em->persist($clothing);
            $em->flush();
            return $this->redirectToRoute('member_home');
        }
        return $this->render('member/clothes_add.html.twig', ['form' => $form->createView(),
        ]);


    }

    /**
     * @Route("/overzicht", name="overzicht")
     */
    public function overzicht() {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser()->getId();
        $foto = $em->getRepository(ClothingPiece::class)->findBy([
            'user' => $user
        ]);
        return $this->render('member/overzicht.html.twig', [
            'images' => $foto
        ]);
    }

    /**
     * @Route("/clothes/{id}", name="overzicht_aangepast")
     */
    public function overzichtAangepast($id) {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser()->getId();
        $foto = $em->getRepository(ClothingPiece::class)->findBy([
            'user' => $user,
            'Type' => $id

        ]);
        return $this->render('member/overzicht.html.twig', [
            'images' => $foto
        ]);
    }

    /**
     * @Route("/clothes/select/{id}", name="clothes_select")
     */
    public function clothes_select($id) {
        $em = $this->getDoctrine()->getManager();
        $cpiece = $em->getRepository(ClothingPiece::class)->find($id);
        $selected = $cpiece->getSelected();
        if($selected == false){
            $cpiece->setSelected(true);
        } else if($selected == true)
        {
            $cpiece->setSelected(false);
        }
        $em->persist($cpiece);
        $em->flush();
        return $this->redirectToRoute('overzicht');
    }

    /**
     * @Route("/outfit", name="outfit")
     */
    public function outfit() {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser()->getId();
        $clothes = $em->getRepository(ClothingPiece::class)->findBy([
            'user' => $user,
            'selected' => true
        ]);
        $i = 0;
        $size = count($clothes);
        if($size > 2) {
            //error ofzo?
        } elseif( $size == 2) {
            foreach($clothes as $clothes){
            $type = $clothes->getType();
            switch ($type) {
                case 'tshirt' : $bovenstuk = $em->getRepository(ClothingPiece::class)->findBy([
                    'user' => $user,
                    'selected' => true,
                    'Type' => 'tshirt'
                ]); break;
                case 'shirt' : $bovenstuk = $em->getRepository(ClothingPiece::class)->findBy([
                    'user' => $user,
                    'selected' => true,
                    'Type' => 'shirt'
                ]); break;
                case 'blousse' : $bovenstuk = $em->getRepository(ClothingPiece::class)->findBy([
                    'user' => $user,
                    'selected' => true,
                    'Type' => 'blousse'
                ]); break;
                case 'trui': $bovenstuk = $em->getRepository(ClothingPiece::class)->findBy([
                    'user' => $user,
                    'selected' => true,
                    'Type' => 'trui'
                ]);break;
                case 'rok': $onderstuk = $em->getRepository(ClothingPiece::class)->findBy([
                    'user' => $user,
                    'selected' => true,
                    'Type' => 'rok']);
                    break;
                case 'broek' :$onderstuk = $em->getRepository(ClothingPiece::class)->findBy([
                    'user' => $user,
                    'selected' => true,
                    'Type' => 'broek']);
                break;
                default: break;
            }
            $i++;
            }
        } elseif($clothes == 1){
            //jurk
            return $this->render('member/outfit.html.twig', [
                'jurk' => $clothes,
            ]);
        }
        $clothes = $em->getRepository(ClothingPiece::class)->findBy([
            'user' => $user,
            'selected' => true
        ]);
        return $this->render('member/outfit.html.twig', [
            'images' => $clothes,
            'bovenstuk' => $bovenstuk[0],
            'onderstuk' => $onderstuk[0]
        ]);
    }

    /**
     * @Route("/face", name="face")
     */
    public function face(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser()->getId();
        $person = $em->getRepository(User::class)->find($user);

        $form = $this->createForm(FaceImageType::class, $person);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            /**$var UploadedFile $imageFile*/
            $imageFile = $form->get('face_image')->getData();
            if($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL

                $imageownername = $this->getUser()->getUsername();
                $safeFilename = 'face' .'-'. $imageownername;
                $newFilename = $safeFilename.'-'.uniqid().'-'.$imageFile->guessExtension();

                //Move the file to the directory where images are stored
                try{
                    $imageFile->move($this->getParameter('face_directory'), $newFilename);
                } catch (FileException $e) {
                    //handle excetion if something happens during file upload
                }
                $person->setFaceImage($newFilename);
            }
            $clothing = $form->getData();
            $em->persist($person);
            $em->flush();
            return $this->redirectToRoute('/home');
        }
        return $this->render('member/face.html.twig', ['form' => $form->createView(),
        ]);
    }

}

templates/member/clothes_add.html.twig
{% extends 'member/nav_bar.html.twig' %}
{% block body %}
    {{ form(form) }}
{% endblock %}

templates/member/face.html.twig
{% extends 'member/nav_bar.html.twig' %}
{% block body %}
    {{ form(form) }}
{% endblock %}

templates/member/homepage.html.twig
{% extends 'member/nav_bar.html.twig' %}
{% block body %}

{% endblock %}

templates/member/jurk.html.twig
{% extends 'member/nav_bar.html.twig' %}
{% block body %}
    <img src="{{ asset('img/elmo.jpg') }}"><br>
        <img style="width: 30%; height: 20vh;"  src="{{ jurk.uri }}"> <br>
{% endblock %}

templates/member/nav_bar.html.twig
{% extends 'base.html.twig' %}
{% block nav %}
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
    </head>
    <div class="jumbotron p-3 row" style="margin-bottom:0;">
        <img  class="col-sm-2 col-lg-1" style="height: 140px" src="{{ asset('img/elmo.jpg') }}" alt="logo">
        <div class="col-sm-8 col-lg-9">
            <h1>PassFD</h1>
        </div>
        <div class="col-sm-2 col-lg-1 d-flex flex-column">
            <p>Welkom</p>
            <p> Visitor </p>
            <a href="/logout" class="btn btn-outline-danger">Logout</a>
        </div>
    </div>
    <nav class="navbar navbar-expand-sm">
        <a class="navbar-brand text-danger" href="{{ path('member_home') }}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link text-danger" href="{{ path('face') }}">Face</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-danger" href="{{ path('overzicht') }}">Overzicht</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link text-danger dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Kleding
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class=" nav-link text-danger dropdown-item" href="{{ path('clothes_add')}}">Toevoegen</a>
                        <a class=" nav-link text-danger dropdown-item" href="{{ path('overzicht_aangepast', {id: 'broek'}) }}">Broek</a>
                        <a class=" nav-link text-danger dropdown-item" href="{{ path('overzicht_aangepast', {id: 'tshirt'}) }}">T-shirt</a>
                        <a class=" nav-link text-danger dropdown-item" href="{{ path('overzicht_aangepast', {id: 'shirt'}) }}">Shirt</a>
                        <a class=" nav-link text-danger dropdown-item" href="{{ path('overzicht_aangepast', {id: 'blousse'}) }}">Blousse</a>
                        <a class=" nav-link text-danger dropdown-item" href="{{ path('overzicht_aangepast', {id: 'rok'}) }}">Rok</a>
                        <a class=" nav-link text-danger dropdown-item" href="{{ path('overzicht_aangepast', {id: 'jurk'}) }}">Jurk</a>
                        <a class=" nav-link text-danger dropdown-item" href="{{ path('overzicht_aangepast', {id: 'trui'}) }}">Trui</a>
                        <a class=" nav-link text-danger dropdown-item" href="{{ path('overzicht')}}">Alles</a>
                    </div>

                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

templates/member/outfit.html.twig
{% extends 'member/nav_bar.html.twig' %}
{% block body %}
    <img src="{{ asset('img/elmo.jpg') }}"><br>
    <img style="width: 30%; height: 20vh;"  src="{{ bovenstuk.uri }}"> <br>
    <img style="width: 30%; height: 20vh;"  src="{{ onderstuk.uri }}"> <br>
{% endblock %}

templates/member/overzicht.html.twig
{% extends 'member/nav_bar.html.twig' %}
{% block body %}
    <table class="table">
        <thead>
        <th>Naam</th>
        <th>Style</th>
        <th>Maat</th>
        <th>Kleur</th>
        <th></th>
        <th></th>
        </thead>
 {% for image in images %}
     <tr>
     <td>{{ image.name }}</td>
         <td> {{ image.style }}</td>
         <td>{{ image.size }}</td>
         <td>{{ image.color }}</td>
    <td><img style="width: 150px; height: 200px;"src="{{ image.uri }}"></td>
          {% if image.selected != 1 %}
         <td><a href="{{ path('clothes_select', {id: image.id}) }}"><button class="btn btn-outline-danger">Selecteer</button></a></td>
         {% else %}
             <td><a href="{{ path('clothes_select', {id: image.id}) }}"><button class="btn btn-outline-success">Geselecteer</button></a></td>
             {% endif %}
     </tr>
 {% endfor %}
    </table>
{% endblock %}

templates/member/show_img.twig
{% extends 'member/nav_bar.html.twig' %}
{% block body %}
    <img src="{{ image }}">

{% endblock %}